# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "741fce976eb36e0ff8c5e62c0230a15c"
application_url = "https://its-quarters-control-royal.trycloudflare.com"
embedded = true
name = "RankPilot AI"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,read_locations,write_pixels,read_customer_events"

[webhooks]
api_version = "2026-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "/webhooks/customers/redact"
  customer_data_request_url = "/webhooks/customers/data_request"
  shop_deletion_url = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://its-quarters-control-royal.trycloudflare.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
