# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "741fce976eb36e0ff8c5e62c0230a15c"
name = "RankPilot AI"
application_url = "https://rankpilotai.alsanlab.cloud"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "/webhooks/customers/redact"
  customer_data_request_url = "/webhooks/customers/data_request"
  shop_deletion_url = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
scopes = "read_inventory,read_locations,read_products,write_products,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://rankpilotai.alsanlab.cloud/api/auth"
]