# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a75084d5f91f886acac377b53aa6d554"
name = "RankPilot AI Advance"
application_url = "https://rankpilotai.alsanlab.cloud"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "/webhooks/customers/redact"
  customer_data_request_url = "/webhooks/customers/data_request"
  shop_deletion_url = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
scopes = "read_products,write_products,read_inventory,read_locations,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://rankpilotai.alsanlab.cloud/api/auth",
  "https://rankpilotai.alsanlab.cloud/auth/callback",
  "https://rankpilotai.alsanlab.cloud/auth/shopify/callback",
  "https://rankpilotai.alsanlab.cloud/api/auth/callback"
]